name: Deploy Tagged FE Service to Prod
on:
  workflow_dispatch:
  push:
    tags:
      - 'deploy-singsaver-*'
      - 'deploy-moneyhero-*'
      - 'deploy-money101-*'
      - 'deploy-moneyguru-*'
      - 'deploy-moneymax-*'
      - 'deploy-comparehero-*'

jobs:
  deploy:
    name: Deploy simulation
    runs-on: ubuntu-latest

    steps:
      - name: Log Last Release Tag        
        run: echo Hello