# This is a basic workflow to help you get started with Actions

name: TagDeployment
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      market:
        type: choice
        description: "Please select a market"
        options:
        - all
        - singsaver
        - moneyhero
        - money101
        - comparehero
        - moneyguru
        - moneymax
        required: true
        default: "all"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Preperation
        run: echo ${{ github.event.inputs.market }}

      - name: CreateTag
        run: |
        createTag () {
          local market=$1
          local version=`git rev-parse --short HEAD`
          local tag=deploy-$market-$version

          echo 'Create tag:' $tag
          git tag $tag
          git push origin $tag
        }